[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "monnect"
version = "1.0.1"
description = "Automatically connect or disconnect a Bluetooth speaker when a specific display is connected on macOS."
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Ankit Gupta" }
]
license = { text = "MIT" }

classifiers = [
  "Operating System :: MacOS",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "License :: OSI Approved :: MIT License",
  "Environment :: Console"
]

dependencies = []

[project.urls]
Homepage = "https://github.com/aki21j/Monnect"

[project.scripts]
monnect = "monnect.cli:main"
